// TENANT AUTHENTICATION
export const TENANT_LOADING = 'TENANT_LOADING';
export const TENANT_LOADED = 'TENANT_LOADED';
export const TENANT_AUTH_ERROR = 'TENANT_AUTH_ERROR';
export const TENANT_LOGIN_SUCCESS = 'TENANT_LOGIN_SUCCESS';
export const TENANT_LOGIN_FAIL = 'TENANT_LOGIN_FAIL';
export const TENANT_LOGOUT_SUCCESS = 'TENANT_LOGOUT_SUCCESS';
export const TENANT_REGISTER_SUCCESS = 'TENANT_REGISTER_SUCCESS';
export const TENANT_REGISTER_FAIL = 'TENANT_REGISTER_FAIL';
export const ATTEMPT_TENANT_LOGIN = 'ATTEMPT_TENANT_LOGIN';
export const ATTEMPT_TENANT_LOGIN_FAILED = 'ATTEMPT_TENANT_LOGIN_FAILED';
export const RESET_TENANT_LOGIN_FAILED = 'RESET_TENANT_LOGIN_FAILED';
export const AFTER_TENANT_LOAD = 'AFTER_TENANT_LOAD';

// USER AUTHENTICATION
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const ATTEMPT_USER_LOGIN = 'ATTEMPT_USER_LOGIN';
export const ATTEMPT_USER_LOGIN_FAILED = 'ATTEMPT_USER_LOGIN_FAILED';
export const RESET_USER_LOGIN_FAILED = 'RESET_USER_LOGIN_FAILED';
export const AFTER_USER_LOAD = 'AFTER_USER_LOAD';

// ERROR
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


// CUSTOMERS
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const CUSTOMERS_LOADING = "CUSTOMERS_LOADING";

// CURRENT CUSTOMER
export const GET_CURRENT_CUSTOMER ="GET_CURRENT_CUSTOMER";
export const CURRENT_CUSTOMER_LOADING ="CURRENT_CUSTOMER_LOADING";
export const GET_CURRENT_CUSTOMER_TICKETS = "GET_CURRENT_CUSTOMER_TICKETS";
export const CURRENT_CUSTOMER_TICKETS_LOADING = "CURRENT_CUSTOMER_TICKETS_LOADING";


// TICKETS
export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const TICKETS_LOADING = "TICKETS_LOADING";
export const RESET_TICKET_CREATED = "RESET_TICKET_CREATED";

// CURRENT TICKET
export const GET_CURRENT_TICKET ="GET_CURRENT_TICKET";
export const CURRENT_TICKET_LOADING ="CURRENT_TICKET_LOADING";


// PRIORITIES
export const GET_PRIORITIES = "GET_PRIORITIES";
export const PRIORITIES_LOADING = "PRIORITIES_LOADING";


// CATEGORIES
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";


// SUB_CATEGORIES
export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
export const ADD_SUB_CATEGORY = "ADD_SUB_CATEGORY";
export const SUB_CATEGORIES_LOADING = "SUB_CATEGORIES_LOADING";


// STATUSES
export const GET_STATUSES = "GET_STATUSES";
export const ADD_STATUS = "ADD_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const STATUSES_LOADING = "STATUSES_LOADING";


// GROUPS
export const GET_GROUPS = "GET_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const GROUPS_LOADING = "GROUPS_LOADING";

// AGENTS
export const GET_AGENTS = "GET_AGENTS";
export const ADD_AGENT = "ADD_AGENT";
export const AGENTS_LOADING = "AGENTS_LOADING";
export const RESET_AGENT_CREATED = "RESET_AGENT_CREATED";


// CURRENT AGENT
export const GET_CURRENT_AGENT ="GET_CURRENT_AGENT";
export const CURRENT_AGENT_LOADING ="CURRENT_AGENT_LOADING";


// USERS
export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING";
export const RESET_USER_CREATED = "RESET_USER_CREATED";


// TAGS
export const GET_TAGS = "GET_TAGS";
export const ADD_TAG = "ADD_TAG";
export const TAGS_LOADING = "TAGS_LOADING";